In [4]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
import numpy as np

In [5]:
"""
File Reading
"""
a = []
for i in range(14,31):
    try:
        for j in range(100):
            with open("../TrainingData/TeslaTrainingData_2019-10-"+str(i)+"/Tesla"+str(j)+".txt", mode='rb') as file:
                try:
                    a.append(str(file.read()))
                except Exception as e:
                    print(e)
                    print(file.name)
    except:
        print("10/"+str(i))
for i in range(1,30):
    if i != 10:
        try:
            for j in range(100):
                with open("../TrainingData/TeslaTrainingData_2019-11-"+str(i)+"/Tesla"+str(j)+".txt", mode='rb') as file:
                    try:
                        a.append(str(file.read()))
                    except Exception as e:
                        print(file.name)
        except:
            print("11/"+str(i))
print(len(a))

10/19
10/20
10/26
10/27
11/2
11/3
11/9
11/16
11/17
11/22
11/23
11/24
3300


In [21]:
"""
Neural Network Model Creation
"""
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Dense, Input, LSTM, Embedding, Dropout, Activation
from tensorflow.keras.layers import Bidirectional, GlobalMaxPool1D
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras import layers
x_train = np.array(a, dtype=np.str)
x_train = x_train.astype(str)
# print(x_train.shape)
y_train = np.zeros(2700)+0.9
print(y_train.shape)
import tensorflow as tf
embed_size = 300 
max_features = 50000 
maxlen = 100
tokenizer = Tokenizer(num_words=max_features)
tokenizer.fit_on_texts(list(x_train))
x_train = tokenizer.texts_to_sequences(x_train)
model1 = tf.keras.Sequential()
model1.add(Embedding(max_features, embed_size, input_length=maxlen))
model1.add(Bidirectional(LSTM(128, return_sequences=True)))
model1.add(GlobalMaxPool1D())
model1.add(Dense(128, activation='relu'))
model1.add(Dense(32, activation='relu'))
model1.add(Dense(16, activation='relu'))
model1.add(Dense(8, activation='relu'))
model1.add(Dense(2,activation='softmax'))
model1.compile(loss='sparse_categorical_crossentropy', optimizer=tf.keras.optimizers.Adam(), metrics=['accuracy'])
model1.summary()
x_trainR = np.array(x_train)[:2200]
y_trainR = np.array(y_train)[:2200]
x_test = np.array(x_train)[2200:]
y_test = np.array(y_train)[2200:]
x_train = x_trainR
y_train = y_trainR
x_train = pad_sequences(x_train, maxlen=maxlen)
x_test = pad_sequences(x_test, maxlen=maxlen)

(2700,)
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 100, 300)          15000000  
_________________________________________________________________
bidirectional_1 (Bidirection (None, 100, 256)          439296    
_________________________________________________________________
global_max_pooling1d_1 (Glob (None, 256)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_5 (Dense)              (None, 32)                4128      
_________________________________________________________________
dense_6 (Dense)              (None, 16)                528       
_________________________________________________________________
dense_7 (Dense)              (None, 8)        

In [22]:
"""
Formats data labels
"""
def toFinal(a):
    for i in range(len(a)):
        if a[i] > 0:
            a[i] = 1
        else:
            a[i] = 0

In [23]:
"""
Reads and formats data labels
"""
y_train = []
for i in range(14,32):
    try:
        with open("../TrainingData/TeslaTrainingData_2019-10-"+str(i)+"/Tesla.csv") as file:
            j = file.read().split(',')[1]
            assert j is not None
            j = j.replace('\n','')
            for _ in range(100):
                y_train.append(float(j))
    except:
        print("Bad: 10/"+str(i))
for i in range(1,22):
    try:
        with open("../TrainingData/TeslaTrainingData_2019-11-"+str(i)+"/Tesla.csv") as file:
            j = file.read().split(',')[1]
            assert j is not None
            j = j.replace('\n','')
            for _ in range(100):
                y_train.append(float(j))
    except:
        print("Bad: 11/"+str(i))
toFinal(y_train)
# print(y_train)
y_train = np.array(y_train)
# print(y_train)
print(y_train.shape)
print(x_train.shape)


Bad: 10/19
Bad: 10/20
Bad: 10/23
Bad: 10/25
Bad: 10/26
Bad: 10/27
Bad: 11/2
Bad: 11/3
Bad: 11/9
Bad: 11/10
Bad: 11/16
Bad: 11/17
(2700,)
(2200, 100)


In [28]:
print(np.count_nonzero(y_train))
print(y_train.size)
y_train = y_train[:1500]
x_train = x_train[:2200]

1400
2200


In [ ]:
"""
Trains Model
"""
history = model1.fit(x_train, y_train, epochs=200, batch_size=100)

Train on 1500 samples
Epoch 1/200
1500/1500 [==============================] - 12s 8ms/sample - loss: 0.6929 - accuracy: 0.5333
Epoch 2/200
1500/1500 [==============================] - 9s 6ms/sample - loss: 0.6911 - accuracy: 0.5333
Epoch 3/200
1500/1500 [==============================] - 9s 6ms/sample - loss: 0.6896 - accuracy: 0.5333
Epoch 4/200
1500/1500 [==============================] - 9s 6ms/sample - loss: 0.6884 - accuracy: 0.5333
Epoch 5/200
1500/1500 [==============================] - 9s 6ms/sample - loss: 0.6852 - accuracy: 0.5287
Epoch 6/200
1500/1500 [==============================] - 9s 6ms/sample - loss: 0.6797 - accuracy: 0.5520
Epoch 7/200
1500/1500 [==============================] - 11s 7ms/sample - loss: 0.6753 - accuracy: 0.5707
Epoch 8/200
1500/1500 [==============================] - 9s 6ms/sample - loss: 0.6690 - accuracy: 0.5760
Epoch 9/200
1500/1500 [==============================] - 9s 6ms/sample - loss: 0.6738 - accuracy: 0.5627
Epoch 10/200
1500/1500 [=======

In [18]:
def predict(x):
    tokenizer = Tokenizer(num_words=max_features)
    tokenizer.fit_on_texts(list(x))
    x =pad_sequences(tokenizer.texts_to_sequences(x), maxlen=maxlen)
    return model1.predict(x)

In [19]:
print(model1.weights)

[<tf.Variable 'embedding/embeddings:0' shape=(50000, 300) dtype=float32, numpy=
array([[ 0.03498546, -0.01473368,  0.00580215, ...,  0.01270312,
        -0.00630977, -0.05688262],
       [ 0.00413679, -0.03184727, -0.04803321, ...,  0.01632361,
         0.02689   , -0.05694659],
       [ 0.0532416 ,  0.01232925, -0.04633527, ...,  0.00021526,
        -0.01948338, -0.07421148],
       ...,
       [-0.04614413,  0.03991515,  0.0294464 , ..., -0.0416157 ,
         0.00676612, -0.01475601],
       [ 0.00618427,  0.0092067 ,  0.00890341, ..., -0.01048785,
         0.02362057, -0.00103893],
       [ 0.02417636, -0.0289183 ,  0.01927852, ...,  0.04732117,
        -0.0267395 ,  0.04819292]], dtype=float32)>, <tf.Variable 'bidirectional/forward_lstm/kernel:0' shape=(300, 512) dtype=float32, numpy=
array([[ 0.12731835, -0.07421365, -0.09264964, ...,  0.06707245,
         0.00698306, -0.04800601],
       [-0.0887736 ,  0.03444036, -0.01086832, ...,  0.08801305,
         0.01525536,  0.03890301],


In [20]:
predict('Hello Alex')

array([[0.48836675, 0.5116333 ],
       [0.5013016 , 0.49869844],
       [0.4916941 , 0.5083059 ],
       [0.4916941 , 0.5083059 ],
       [0.50001127, 0.4999887 ],
       [0.4812158 , 0.5187842 ],
       [0.49010134, 0.5098986 ],
       [0.4916941 , 0.5083059 ],
       [0.5013016 , 0.49869844],
       [0.50526404, 0.49473593]], dtype=float32)